### ISSUE TITLE
Fatal Error Call to a member function rollback() on null

### ISSUE THREAD

**Issue by bloomfieldcollege** [drupal-composer/info-rewrite#18]
Hi,

I hope this is the right place to post this, and if it's not, I apologize. I'm getting this error:

PHP Fatal error:  Uncaught Error: Call to a member function rollback() on null in /drupalpath/vendor/drupal-composer/info-rewrite/src/DrupalInfo.php:138
Stack trace:
#0 /drupalpath/vendor/drupal-composer/info-rewrite/src/DrupalInfo.php(111): DrupalComposer\Composer\DrupalInfo->doRollback(Object(Composer\Package\AliasPackage))
#1 [internal function]: DrupalComposer\Composer\DrupalInfo->rollbackRewrite(Object(Composer\Script\Event))
#2 phar:///usr/local/Cellar/composer/1.8.0/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))
#3 phar:///usr/local/Cellar/composer/1.8.0/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#4 phar:///usr/local/Cellar/composer/1.8.0/bin/composer/src/Composer/Installer.php(205): Composer\EventDispatcher\EventDispatcher->dispatchScript('pre-update-cmd', true) in /drupalpath/vendor/drupal-composer/info-rewrite/src/DrupalInfo.php on line 138

Fatal error: Uncaught Error: Call to a member function rollback() on null in /drupalpath/vendor/drupal-composer/info-rewrite/src/DrupalInfo.php:138
Stack trace:
#0 /drupalpath/vendor/drupal-composer/info-rewrite/src/DrupalInfo.php(111): DrupalComposer\Composer\DrupalInfo->doRollback(Object(Composer\Package\AliasPackage))
#1 [internal function]: DrupalComposer\Composer\DrupalInfo->rollbackRewrite(Object(Composer\Script\Event))
#2 phar:///usr/local/Cellar/composer/1.8.0/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))
#3 phar:///usr/local/Cellar/composer/1.8.0/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#4 phar:///usr/local/Cellar/composer/1.8.0/bin/composer/src/Composer/Installer.php(205): Composer\EventDispatcher\EventDispatcher->dispatchScript('pre-update-cmd', true) in /drupalpath/vendor/drupal-composer/info-rewrite/src/DrupalInfo.php on line 138

I'm not sure what to do.

**Comment by jhedstrom** [comment]
To fix the immediate error you could just remove the module (or theme) and then run `composer install`--this error is happening on rollback for some reason. We could probably harden the logic around the error here:

```
    /**
     * Process an info file rollback for a given package.
     * @param PackageInterface $package
     */
    protected function doRollback(PackageInterface $package)
    {
        $writer = $this->getWriter($package);
        $writer->rollback();
    }
```

for whatever reason, a corresponding write class isn't being found, thus the fatal error. So that above logic could throw a better exception/error with relevant details, or just log the error as a warning and allow composer to continue on.

**Comment by jhedstrom** [comment]
Thanks for the report! This should be fixed in the latest version now.

**Comment by RishiKulshreshtha** [comment]
This was reported while using `Composer version 1.10.5 2020-04-10 11:44:22`. 

Though it got bypassed once I removed/deleted the `vendor` directory and executed the `composer install` command.
