### ISSUE TITLE
Event subscriptions weight

### ISSUE THREAD

**Issue by super-romeo** [drupal-composer/info-rewrite#21]
Plugin cweagans/composer-patches has POST_PACKAGE_INSTALL and POST_PACKAGE_UPDATE = 10. Your plugin has 50. Because of this some patches altered .info file cannot be applied...

This fixes this problem:
>$events[PackageEvents::POST_PACKAGE_INSTALL] = ['writeInfoFiles', 5];
>$events[PackageEvents::POST_PACKAGE_UPDATE] = ['writeInfoFiles', 5];

**Comment by lkmorlan** [comment]
These lines are removed by #26.

**Comment by jhedstrom** [comment]
I think this is fixed then. Thanks all!
