### ISSUE TITLE
core_version_requirement' constraint

### ISSUE THREAD

**Issue by nevergone** [drupal-composer/info-rewrite#22]
I updated the poll module dev version with info-rewrite plugin, but I get the following drush error:

The 'core_version_requirement' constraint (^8.7.7 || ^9) requires the 'core' key not be set in modules/contrib/poll/poll.info.yml

Please not add core key, if core_version_requirement is available.

**Comment by Pasqualle** [comment]
I can confirm this problem with other modules also, and it is a fatal error, not just drush issue:

Drupal\Core\Extension\InfoParserException: The 'core_version_requirement' constraint (^8.7.7 || ^9) requires the 'core' key not be set in modules/contrib/entity_browser/entity_browser.info.yml in Drupal\Core\Extension\InfoParserDynamic->parse() (line 81 of core/lib/Drupal/Core/Extension/InfoParserDynamic.php).

**Comment by geek-andi** [comment]
I'm also running into this: `The 'core_version_requirement' constraint (^8.7.7 || ^9) requires the 'core' key not be set in modules/contrib/prevent_unsafe_login/prevent_unsafe_login.info.yml `

**Comment by geek-andi** [comment]
See <a href="https://www.drupal.org/node/3070687">New 'core_version_requirement' key in info.yml files for modules, themes and profiles allows Composer semantic version constraints including specifying multiple major versions of core | Drupal.org</a>

> For example a module that is compatible with Drupal 8 versions after Drupal 8.8.0 and also Drupal 9 will need a info.yml file like this:
> 
> name: My Module
> type: module
> core_version_requirement: ^8.8 || ^9
> 
> The core: key must not be used here to make sure that versions of Drupal before 8.7.7 will not install the module. Adding both core and core_version_requirement with anything other than core_version_requirement: ^8 || ^9 will result in an exception.

**Comment by geek-merlin** [comment]
See PR #23

**Comment by lkmorlan** [comment]
A fix with coding standards correct and tests passing is in #28.
