### ISSUE TITLE
Changes are rolled-back by additional calls to `composer install`

### ISSUE THREAD

**Issue by lkmorlan** [drupal-composer/info-rewrite#25]
If I run `composer install` version numbers are added. If I run it again, rollbackRewrite() removes the version numbers but they do not get added back again. I think this is because neither POST_PACKAGE_INSTALL nor POST_PACKAGE_UPDATE get run for packages that do not need to be changed on the subsequent run of `composer install`.

**Comment by lkmorlan** [comment]
This can be solved by having a method which runs on POST_INSTALL_CMD and POST_UPDATE_CMD which rollbackRewrite() but calls doWriteInfoFiles() instead of doRollback(). I've tested this and it works. Would you like me to write up a pull request with this?

**Comment by jhedstrom** [comment]
Yeah, that would be awesome! Thanks for digging into this.

**Comment by lkmorlan** [comment]
My solution is in #26.
