### ISSUE TITLE
Don't rewrite info files that already have version info

### ISSUE THREAD

**Issue by jhedstrom** [drupal-composer/info-rewrite#3]

**Comment by eelkeblok** [comment]
I've run into a very similar (of not the same) problem with updating core. I added this with the require command from the readme and did get the latest commit (b566d669891cae4ee4bbb75fd97cecfcace6cab5 at the time of writing). I subsequently updated Drupal core using composer update drupal/core --with-dependencies and noticed that the version reported for Drupal core was 8.3.2.0, which threw off the update manager completely. Checking in system.info.yml, it was reported that the file was rewritten by this component.

**Comment by eelkeblok** [comment]
Scratch that, I've just noticed that the core files do not have version information without the component installed. So it probably should be adding the version info, except that it inserts an incorrect version. I've created a new issue for that, #5.
